fix: add ValidateHttpRequestSync method for synschronous request validation
pb33f/libopenapi-validator pull request #80
Opened 2024-05-03 13:40 UTC by commoddity

Implements the feature requested in: https://github.com/pb33f/libopenapi-validator/issues/79

2024-05-03 14:00 UTC, daveshanley commented
Missing a few lines of coverage, as soon as it's bumped, I can merge this in!

2024-05-03 15:43 UTC, commoddity commented
> Missing a few lines of coverage, as soon as it's bumped, I can merge this in!

Thank you. Have just pushed a commit that I believe should cover those 3 missing lines.

2024-05-03 16:50 UTC, daveshanley commented on requests/validate_body.go
> +		fmt.Println("HERE!!!!")
This needs to be removed!

2024-05-03 17:10 UTC, daveshanley requested changes
Looks good to me, if you remove that print statement on line 25 in `validate_body.go` then it's good to go!

2024-05-03 17:39 UTC, commoddity commented on requests/validate_body.go
> +		fmt.Println("HERE!!!!")
Oops! It certainly does. Removed.

2024-05-03 17:40 UTC, commoddity commented
> Looks good to me, if you remove that print statement on line 25 in `validate_body.go` then it's good to go!

Sounds good, I've updated to remove that print.

2024-05-04 12:57 UTC, daveshanley approved these changes
LGTM!

2024-05-04 12:57 UTC, merged